send_metrics = false

name = "shamim-website"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[build]
command = "bun run build"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability.logs]
enabled = true

[vars]
NODE_ENV = "production"
